<script data-template='oi-thumbnail' type='text/x-magento-tmpl'>
	<img src='<%- image %>' id='option_image_<%- id %>' style='display:none;' class='oi-image'/>   
</script>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "optionImages": {                 
                "clickToEnlargeText"  : "<?php echo __('Click to Enlarge'); ?>",
                "spacer"              : "<?php echo $this->getViewFileUrl('Dfe_Logo::images/spacer.gif'); ?>",
                "config" : <?php echo $this->getDataJson() ?>
            }
        }
    }
</script>
