<?php
/** @var $block \Magento\Catalog\Block\Adminhtml\Product\Helper\Form\Gallery\Content */
$n = $block->getElement()->getName() . '[images]';
$f = $block->getFormName();
?>

<div class="row">
	<div class="add-video-button-container">
		<button id="add_video_button"
				title="<?php echo $block->escapeHtml(__('Add Video'));?>"
				data-role="add-video-button"
				type="button"
				class="action-secondary"
				data-ui-id="widget-button-1">
			<span><?php echo $block->escapeHtml(__('Add Video')) ?></span>
		</button>
	</div>
</div>

<?php
/** @var $block \Magento\Catalog\Block\Adminhtml\Product\Helper\Form\Gallery\Content */
$element = $block->getElement();
$elementToggleCode = $element->getToggleCode() ? $element->getToggleCode() : 'toggleValueElements(this, this.parentNode.parentNode.parentNode)';
?>

<div id="<?php echo $block->getHtmlId() ?>"
	 class="gallery"
	 data-mage-init='{"openVideoModal":{}}'
	 data-parent-component="<?php echo $block->escapeHtml($block->getData('config/parentComponent')) ?>"
	 data-images="<?php echo $block->escapeHtml($block->getImagesJson()) ?>"
	 data-types="<?php echo $block->escapeHtml(
		 $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($block->getImageTypes())
	 ) ?>"
>

	<?php
	if (!$block->getElement()->getReadonly()):
		?>
		<div class="image image-placeholder">
			<?= $block->getUploaderHtml(); ?>
			<div class="product-image-wrapper">
				<p class="image-placeholder-text">
					<?php echo $block->escapeHtml(
						__('Browse to find or drag image here')
					); ?>
				</p>
			</div>
		</div>
		<?= $block->getChildHtml('additional_buttons'); ?>
		<?php
	endif;
	?>
	<?php
	foreach ($block->getImageTypes() as $typeData):
		?>
		<input name="<?php echo $block->escapeHtml($typeData['name']) ?>"
			   data-form-part="<?= $f ?>"
			   class="image-<?php echo $block->escapeHtml($typeData['code']) ?>"
			   type="hidden"
			   value="<?php echo $block->escapeHtml($typeData['value']) ?>"/>
		<?php
	endforeach;
	?>
	<script id="<?= $block->getHtmlId() ?>-template" data-template="image" type="text/x-magento-template">
		<div class="image item <% if (data.disabled == 1) { %>hidden-for-front<% } %>  <% if (data.video_url) { %>video-item<% } %>"
			 data-role="image">
			<input type="hidden"
				   name="<?= $n ?>[<%- data.file_id %>][position]"
				   value="<%- data.position %>"
				   data-form-part="<?= $f ?>"
				   class="position"/>
			<% if (data.media_type !== 'external-video') {%>
			<input type="hidden"
				   name="<?= $n ?>[<%- data.file_id %>][media_type]"
				   data-form-part="<?= $f ?>"
				   value="image"/>
			<% } else { %>
			<input type="hidden"
				   name="<?= $n ?>[<%- data.file_id %>][media_type]"
				   value="<%- data.media_type %>"
				   data-form-part="<?= $f ?>"/>
			<% } %>
			<input type="hidden"
				   name="<?= $n ?>[<%- data.file_id %>][video_provider]"
				   value="<%- data.video_provider %>"
				   data-form-part="<?= $f ?>"/>
			<input type="hidden"
				   name="<?= $n ?>[<%- data.file_id %>][file]"
				   value="<%- data.file %>"
				   data-form-part="<?= $f ?>"/>
			<input type="hidden"
				   name="<?= $n ?>[<%- data.file_id %>][value_id]"
				   value="<%- data.value_id %>"
				   data-form-part="<?= $f ?>"/>
			<input type="hidden"
				   name="<?= $n ?>[<%- data.file_id %>][label]"
				   value="<%- data.label %>"
				   data-form-part="<?= $f ?>"/>
			<input type="hidden"
				   name="<?= $n ?>[<%- data.file_id %>][disabled]"
				   value="<%- data.disabled %>"
				   data-form-part="<?= $f ?>"/>
			<input type="hidden"
				   name="<?= $n ?>[<%- data.file_id %>][removed]"
				   value="" class="is-removed"
				   data-form-part="<?= $f ?>"/>
			<input type="hidden"
				   name="<?= $n ?>[<%- data.file_id %>][video_url]"
				   value="<%- data.video_url %>"
				   data-form-part="<?= $f ?>"/>
			<input type="hidden"
				   name="<?= $n ?>[<%- data.file_id %>][video_title]"
				   value="<%- data.video_title %>"
				   data-form-part="<?= $f ?>"/>
			<input type="hidden"
				   name="<?= $n ?>[<%- data.file_id %>][video_description]"
				   value="<%- data.video_description %>"
				   data-form-part="<?= $f ?>"/>
			<input type="hidden"
				   name="<?= $n ?>[<%- data.file_id %>][video_metadata]"
				   value="<%- data.video_metadata %>"
				   data-form-part="<?= $f ?>"/>
			<input type="hidden"
				   name="<?= $n ?>[<%- data.file_id %>][role]"
				   value="<%- data.video_description %>"
				   data-form-part="<?= $f ?>"/>

<!-- 2018-03-25 https://www.upwork.com/d/contracts/19713438 -->
<input
	data-form-part='<?= $f ?>'
	name='<?= $n ?>[<%- data.file_id %>][logo_left]'
	type='hidden'
	value='<%- data.logo_left %>'
/>
<input
	data-form-part='<?= $f ?>'
	name='<?= $n ?>[<%- data.file_id %>][logo_top]'
	type='hidden'
	value='<%- data.logo_top %>'
/>
<input
	data-form-part='<?= $f ?>'
	name='<?= $n ?>[<%- data.file_id %>][logo_scale]'
	type='hidden'
	value='<%- data.logo_scale %>'
/>

			<div class="product-image-wrapper">
				<img class="product-image"
					 data-role="image-element"
					 src="<%- data.url %>"
					 alt="<%- data.label %>"/>

				<div class="actions">
					<button type="button"
							class="action-remove"
							data-role="delete-button"
							title="<% if (data.media_type == 'external-video') {%>
							<?php echo $block->escapeHtml(
								__('Delete video')
							); ?>
						<%} else {%>
							<?php echo $block->escapeHtml(
								__('Delete image')
							); ?>
						<%}%>">
					<span>
						<% if (data.media_type == 'external-video') { %>
						<?php echo $block->escapeHtml(
							__('Delete video')
						); ?>
						<% } else {%>
						<?php echo $block->escapeHtml(
							__('Delete image')
						); ?>
						<%} %>
					</span>
					</button>
					<div class="draggable-handle"></div>
				</div>
				<div class="image-fade"><span><?php echo $block->escapeHtml(
							__('Hidden')
						); ?></span></div>
			</div>

			<div class="item-description">
				<% if (data.media_type !== 'external-video') {%>
				<div class="item-title" data-role="img-title"><%- data.label %></div>
				<div class="item-size">
					<span data-role="image-dimens"></span>, <span data-role="image-size"><%- data.sizeLabel %></span>
				</div>
				<% } else { %>
				<div class="item-title" data-role="img-title"><%- data.video_title %></div>
				<% } %>
			</div>

			<ul class="item-roles" data-role="roles-labels">
				<?php
				foreach ($block->getImageTypes() as $typeData):
					?>
					<li data-role-code="<?php echo $block->escapeHtml(
						$typeData['code']
					) ?>" class="item-role item-role-<?php echo $block->escapeHtml(
						$typeData['code']
					) ?>">
						<?php echo $block->escapeHtml($typeData['label']) ?>
					</li>
					<?php
				endforeach;
				?>
			</ul>
		</div>
	</script>

	<script data-role="img-dialog-container-tmpl" type="text/x-magento-template">
		<div class="image-panel" data-role="dialog">
		</div>
	</script>

	<script data-role="img-dialog-tmpl" type="text/x-magento-template">
		<div class="image-panel-preview">
			<img src="<%- data.url %>" alt="<%- data.label %>" />
		</div>
		<div class="image-panel-controls">
			<strong class="image-name"><%- data.label %></strong>

			<fieldset class="admin__fieldset fieldset-image-panel">
				<div class="admin__field field-image-description">
					<label class="admin__field-label" for="image-description">
						<span><?= __('Alt Text')?></span>
					</label>

					<div class="admin__field-control">
						<textarea 
							class="admin__control-textarea"
							data-role="image-description"
							name="<?= $n ?>[<%- data.file_id %>][label]"
							rows="3"
						><%- data.label %></textarea>
					</div>
				</div>

				<div class="admin__field field-image-role">
					<label class="admin__field-label">
							<span><?php echo $block->escapeHtml(
									__('Role')
								); ?></span>
					</label>
					<div class="admin__field-control">
						<ul class="multiselect-alt">
							<?php
							foreach ($block->getMediaAttributes() as $attribute) :
								?>
								<li class="item">
									<label>
										<input class="image-type"
											   data-role="type-selector"
											   data-form-part="<?= $f ?>"
											   type="checkbox"
											   value="<?php echo $block->escapeHtml(
												   $attribute->getAttributeCode()
											   ) ?>"
										/>
										<?= $block->escapeHtml(
											$attribute->getFrontendLabel()
										) ?>
									</label>
								</li>
								<?php
							endforeach;
							?>
						</ul>
					</div>
				</div>

				<div class="admin__field admin__field-inline field-image-size" data-role="size">
					<label class="admin__field-label">
						<span><?= __('Image Size') ?></span>
					</label>
					<div class="admin__field-value" data-message="<?= __('{size}') ?>"></div>
				</div>

				<div class="admin__field admin__field-inline field-image-resolution" data-role="resolution">
					<label class="admin__field-label">
						<span><?= __('Image Resolution') ?></span>
					</label>
					<div class="admin__field-value" data-message="<?= __('{width}^{height} px') ?>"></div>
				</div>
<!-- 2018-03-20 https://www.upwork.com/d/contracts/19713438 -->
<div class='admin__field admin__field-inline dfe-logo-field'>
	<label class='admin__field-label' for='logo_left'>Logotype Offset Left (%, 0..100)</label>
	<div class='admin__field-control'>
		<input
			class='admin__control-text'
			data-form-part='<?= $f ?>'
			id='logo_left'
			name='<?= $n ?>[<%- data.file_id %>][logo_left]'
			type='text'
			value='<%- data.logo_left %>'
		/>
	</div>
</div>
<div class='admin__field admin__field-inline dfe-logo-field'>
	<label class='admin__field-label' for='logo_top'>Logotype Offset Top (%, 0..100)</label>
	<div class='admin__field-control'>
		<input
			class='admin__control-text'
			data-form-part='<?= $f ?>'
			id='logo_top'
			name='<?= $n ?>[<%- data.file_id %>][logo_top]'
			type='text'
			value='<%- data.logo_top %>'
		/>
	</div>
</div>
<div class='admin__field admin__field-inline dfe-logo-field'>
	<label class='admin__field-label' for='logo_scale'>Logotype Scale (%, 0..100)</label>
	<div class='admin__field-control'>
		<input
			class='admin__control-text'
			data-form-part='<?= $f ?>'
			id='logo_scale'
			name='<?= $n ?>[<%- data.file_id %>][logo_scale]'
			type='text'
			value='<%- data.logo_scale %>'
		/>
	</div>
</div>
				<div class="admin__field field-image-hide">
					<div class="admin__field-control">
						<div class="admin__field admin__field-option">
							<input type="checkbox"
								   id="hide-from-product-page"
								   data-role="visibility-trigger"
								   data-form-part="<?= $f ?>"
								   value="1"
								   class="admin__control-checkbox"
								   name="<?= $n ?>[<%- data.file_id %>][disabled]"
							<% if (data.disabled == 1) { %>checked="checked"<% } %> />

							<label for="hide-from-product-page" class="admin__field-label">
								<?php echo $block->escapeHtml(
									__('Hide from Product Page')
								); ?>
							</label>
						</div>
					</div>
				</div>
			</fieldset>
		</div>
	</script>
	<div id="<?php /* @noEscape */ echo $block->getNewVideoBlockName();?>" style="display:none">
		<?= $block->getFormHtml();?>
		<div id="video-player-preview-location" class="video-player-sidebar">
			<div class="video-player-container"></div>
			<div class="video-information title">
				<label><?php echo $block->escapeHtml(
						__('Title:')
					); ?> </label><span></span>
			</div>
			<div class="video-information uploaded">
				<label><?php echo $block->escapeHtml(
						__('Uploaded:')
					); ?> </label><span></span>
			</div>
			<div class="video-information uploader">
				<label><?php echo $block->escapeHtml(
						__('Uploader:')
					); ?> </label><span></span>
			</div>
			<div class="video-information duration">
				<label><?php echo $block->escapeHtml(
						__('Duration:')
					); ?> </label><span></span>
			</div>
		</div>
	</div>

	<?php echo $block->getChildHtml('new-video'); ?>
</div>
<script>
	jQuery('body').trigger('contentUpdated');
</script>
